# Generated by Django 4.1.7 on 2023-03-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butcher_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
