# Generated by Django 4.1.7 on 2023-02-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butcher_shop_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('phone_number', models.CharField(max_length=12, verbose_name='phone_name')),
                ('comment', models.CharField(max_length=350, verbose_name='comment')),
            ],
        ),
    ]
