# Generated by Django 4.1.7 on 2023-03-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butcher_shop_app', '0002_alter_order_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_items',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_kgs',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
