# Generated by Django 4.1.7 on 2023-03-13 12:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butcher_shop_app', '0003_order_total_cost_order_total_items_order_total_kgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview',
            field=ckeditor.fields.RichTextField(default='Без описания', max_length=500),
        ),
    ]
