# Generated by Django 4.1.7 on 2023-03-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butcher_shop_app', '0004_product_preview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_cost',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
