# Generated by Django 4.1.7 on 2023-03-06 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butcher_shop_app', '0005_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
