# Generated by Django 4.1.7 on 2023-03-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butcher_shop_app', '0005_alter_order_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsinshoppingcart',
            name='count',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
