# Generated by Django 4.1.7 on 2023-03-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butcher_shop_app', '0006_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category_name',
            field=models.ManyToManyField(default='Вне категорий', to='butcher_shop_app.productcategories'),
        ),
    ]
