# Generated by Django 4.1.7 on 2023-03-09 13:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butcher_shop_app', '0007_productcategories_product_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(default='Без описания'),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='img/1.png', upload_to='img'),
        ),
    ]
