# Generated by Django 4.1.7 on 2023-03-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('butcher_shop_app', '0008_remove_product_quantity_product_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='photo',
            new_name='image',
        ),
    ]
