# Generated by Django 4.1.7 on 2023-03-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('butcher_shop_app', '0009_rename_photo_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='img/1.png', max_length=255, upload_to='img'),
        ),
    ]
