# Generated by Django 4.1.7 on 2023-03-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_receipt',
            field=models.BooleanField(default=True),
        ),
    ]
