# Generated by Django 4.1.7 on 2023-03-13 12:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_is_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='preview',
            field=ckeditor.fields.RichTextField(default='', max_length=500),
        ),
    ]
