# Generated by Django 4.1.7 on 2023-03-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='img/1.png', null=True, upload_to='img'),
        ),
    ]
